# Generated by Django 5.2 on 2026-08-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('rice', 'Rice'), ('electricity', 'Electricity'), ('chef', 'Chef'), ('wifi', 'Wifi'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_bills', to='cycles.cycle')),
            ],
            options={
                'ordering': ['-bill_date'],
                'indexes': [models.Index(fields=['cycle', 'bill_type'], name='bills_fixed_cycle_i_e5079f_idx'), models.Index(fields=['cycle', '-bill_date'], name='bills_fixed_cycle_i_878a28_idx')],
            },
        ),
    ]
