# Generated by Django 5.2 on 2026-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedbill',
            name='bill_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('chef', 'Chef'), ('wifi', 'Wifi'), ('gas', 'Gas'), ('garbage', 'Garbage'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
