# Generated by Django 5.0.1 on 2026-07-31 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('computed_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settled', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_cycles', to='cycles.cycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='members.member')),
            ],
            options={
                'ordering': ['cycle__start_date', 'member__name'],
                'unique_together': {('member', 'cycle')},
            },
        ),
    ]
