# Generated by Django 6.0.7 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercycle',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
