# Generated by Django 6.0.7 on 2026-08-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_cycle_fixed_member_rate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('status',), name='unique_open_cycle'),
        ),
    ]
