# Generated by Django 5.2 on 2026-07-31 21:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('breakfast', models.DecimalField(choices=[(Decimal('0'), '0'), (Decimal('0.5'), '½'), (Decimal('1'), '1')], decimal_places=1, default=Decimal('0'), max_digits=3)),
                ('lunch', models.DecimalField(choices=[(Decimal('0'), '0'), (Decimal('1'), '1')], decimal_places=1, default=Decimal('0'), max_digits=3)),
                ('dinner', models.DecimalField(choices=[(Decimal('0'), '0'), (Decimal('1'), '1')], decimal_places=1, default=Decimal('0'), max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='members.membercycle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entry_date', 'member_cycle__member__name'],
                'indexes': [models.Index(fields=['entry_date'], name='meals_meale_entry_d_80c23e_idx')],
                'unique_together': {('member_cycle', 'entry_date')},
            },
        ),
    ]
