# Generated by Django 6.0.7 on 2026-08-02 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='breakfast',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='dinner',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='lunch',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
    ]
